trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  AzSqlDemoDatabase: ""

steps:
- task: UseYUNIQLCLI@0
  inputs:
    version: 'latest'

- task: RunYUNIQLCLI@0
  inputs:
    version: 'latest'
    connectionString: '$(AzSqlDemoDatabase)'
    workspacePath: '$(Build.SourcesDirectory)\sqlserver-samples\visitph-db'
    targetPlatform: 'SqlServer'
    additionalArguments: '--debug'